# Introduction to Numpy

Fast Mathematical Computational Library
Already available library in Python using List is Slow
Homogenous Data structure
Specialized for doing mathematical calculations
High dimensional computation
Inbuilt utilities
Similar to MatLab Library

In [2]:
import numpy as np

In [3]:
a = np.array([2,3,4,5,6,7,8,9])

In [4]:
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Creating the DataType
a = np.array([2,3,4,5,6,7,8,9], dtype=np.float16)
a.dtype
a

array([2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

In [11]:
b = np.array(['Ram','Shyam', 'Seeta', 'Geeta', 'PulkitGoel'])
b

array(['Ram', 'Shyam', 'Seeta', 'Geeta', 'PulkitGoel'], dtype='<U10')

# Zero and One init Matrix

In [13]:
z = np.zeros((4,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
a

array([2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

In [18]:
# zero_like

In [19]:
np.zeros_like(a)

array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float16)

# Ones

In [22]:
y = np.ones((3,3,4))
y

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# Ones_like

In [23]:
np.ones_like(a)

array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float16)

In [ ]:
# Full

In [24]:
np.full((5,5), 'Pulkit')

array([['Pulkit', 'Pulkit', 'Pulkit', 'Pulkit', 'Pulkit'],
       ['Pulkit', 'Pulkit', 'Pulkit', 'Pulkit', 'Pulkit'],
       ['Pulkit', 'Pulkit', 'Pulkit', 'Pulkit', 'Pulkit'],
       ['Pulkit', 'Pulkit', 'Pulkit', 'Pulkit', 'Pulkit'],
       ['Pulkit', 'Pulkit', 'Pulkit', 'Pulkit', 'Pulkit']], dtype='<U6')

# full_like

In [27]:
np.full_like(a, 1234)

array([1234., 1234., 1234., 1234., 1234., 1234., 1234., 1234.],
      dtype=float16)

# Range

Initialize a numpy array from start location to end point. 
Putting Step size provided as parameter excluding the last number

In [29]:
np.arange(10,100, 0.5)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5,
       21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. ,
       26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5,
       32. , 32.5, 33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. ,
       37.5, 38. , 38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5,
       43. , 43.5, 44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. ,
       48.5, 49. , 49.5, 50. , 50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5,
       54. , 54.5, 55. , 55.5, 56. , 56.5, 57. , 57.5, 58. , 58.5, 59. ,
       59.5, 60. , 60.5, 61. , 61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5,
       65. , 65.5, 66. , 66.5, 67. , 67.5, 68. , 68.5, 69. , 69.5, 70. ,
       70.5, 71. , 71.5, 72. , 72.5, 73. , 73.5, 74. , 74.5, 75. , 75.5,
       76. , 76.5, 77. , 77.5, 78. , 78.5, 79. , 79.5, 80. , 80.5, 81. ,
       81.5, 82. , 82.5, 83. , 83.5, 84. , 84.5, 85

In [31]:
np.arange(10,1,-0.1)

array([10. ,  9.9,  9.8,  9.7,  9.6,  9.5,  9.4,  9.3,  9.2,  9.1,  9. ,
        8.9,  8.8,  8.7,  8.6,  8.5,  8.4,  8.3,  8.2,  8.1,  8. ,  7.9,
        7.8,  7.7,  7.6,  7.5,  7.4,  7.3,  7.2,  7.1,  7. ,  6.9,  6.8,
        6.7,  6.6,  6.5,  6.4,  6.3,  6.2,  6.1,  6. ,  5.9,  5.8,  5.7,
        5.6,  5.5,  5.4,  5.3,  5.2,  5.1,  5. ,  4.9,  4.8,  4.7,  4.6,
        4.5,  4.4,  4.3,  4.2,  4.1,  4. ,  3.9,  3.8,  3.7,  3.6,  3.5,
        3.4,  3.3,  3.2,  3.1,  3. ,  2.9,  2.8,  2.7,  2.6,  2.5,  2.4,
        2.3,  2.2,  2.1,  2. ,  1.9,  1.8,  1.7,  1.6,  1.5,  1.4,  1.3,
        1.2,  1.1])

# random
Initialize random values in the matrix

In [35]:
d = np.random.rand(10)
d

array([0.69241072, 0.40892341, 0.0233111 , 0.1881714 , 0.74015315,
       0.14378306, 0.37049883, 0.40017789, 0.80182445, 0.13818532])

In [36]:
e = np.random.rand(4,4)
e

array([[0.46778416, 0.4282393 , 0.64064464, 0.34392275],
       [0.21605473, 0.70756505, 0.95290912, 0.32264412],
       [0.12659816, 0.5156632 , 0.66127187, 0.29608687],
       [0.12983622, 0.47384378, 0.60341449, 0.32263763]])

Initialize array between a range of random values

In [38]:
np.random.randint(5,10,size=(3,3))

array([[7, 9, 9],
       [5, 9, 6],
       [6, 9, 7]])

# shuffle
randomizes the content

In [41]:
print(d)
np.random.shuffle(d)
print(d)

[0.13818532 0.74015315 0.69241072 0.40892341 0.14378306 0.80182445
 0.37049883 0.0233111  0.40017789 0.1881714 ]
[0.1881714  0.37049883 0.69241072 0.74015315 0.40892341 0.80182445
 0.13818532 0.0233111  0.40017789 0.14378306]


# seed
Controls the output, /n
using same seed we will get same output

In [45]:
np.random.seed(1)
np.random.randint(5,10,size=(3,3))

array([[8, 9, 5],
       [6, 8, 5],
       [5, 6, 9]])

# Accessing the elements

In [46]:
np.random.seed(10)
data = np.random.randint(2,20,size=(5,5))
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [49]:
print(data[2][1])

print(data[2,1])


10
10


Accesssing only the first row

In [50]:
data[1]

array([18, 19, 10, 11,  2])

Accessing all rows except first

In [51]:
data[1:]

array([[18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

Accessing till first 2 rows

In [52]:
data[:2]

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2]])

Column access

In [57]:
data[:,1:3]

array([[ 6, 17],
       [19, 10],
       [10,  6],
       [13, 13],
       [16, 19]])

In [56]:
data[:,2:3]

array([[17],
       [10],
       [ 6],
       [13],
       [19]])

Accessing only a slice of Matrix

In [58]:
data[2:4, 2:4]

array([[ 6, 18],
       [13,  3]])

# Shape Size and Dimension
These are not functions but attributes..   Provid information on dimension

In [59]:
data.shape

(5, 5)

In [60]:
data.size

25

ndim --- returns the number of dimensions of a matrix

In [62]:
data.ndim

2

# Reshaping the data
Changes in shap and dimensions of data but not size

In [70]:
a = np.array([1,2,3,4,5,6])

In [71]:
a.shape

(6,)

In [72]:
a.ndim

1

In [74]:
b = a.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
b.ndim

2

In [76]:
b.shape

(2, 3)

In [77]:
b.size

6

In [78]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

# Adding one dimesion

In [81]:
a

array([1, 2, 3, 4, 5, 6])

In [82]:
a.shape

(6,)

In [84]:
a.reshape((a.shape[0],1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [85]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [86]:
data[:, np.newaxis]

array([[[11,  6, 17,  2, 19]],

       [[18, 19, 10, 11,  2]],

       [[12, 10,  6, 18,  6]],

       [[17, 13, 13,  3, 10]],

       [[ 6, 16, 19, 15,  7]]])

# Converting data into one dimesion of 25 elements

In [90]:
data.reshape(25)

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7])

In [91]:
data.reshape(*data.shape,1).shape

(5, 5, 1)

# Removal of dimension converts into 1-D data.. ie flattens the data

In [92]:
np.ravel(data)

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7])

In [ ]:
# Concatenation
Combining 1-D data

In [94]:
x =np.array([1,2,3,4])
y = np.array([5,6,7,8])
np.concatenate([x,y,x,y])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

# Important

0- Vertical Axis.       1- Horizontal Axis 

# Combinig 2-D Data
By default axis 0 ( means Vertical)

In [95]:
data
np.concatenate([data,data])

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [98]:
np.concatenate([data,data], axis=1)

array([[11,  6, 17,  2, 19, 11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2, 18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6, 12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10, 17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7,  6, 16, 19, 15,  7]])

# append
Adds values at the end of the array

In [99]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [100]:
np.append(data,[1,2,3,4,5])

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7,  1,  2,  3,  4,  5])

In [102]:
np.append(data,[[1,2,3,4,5]], axis=0)

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [ 1,  2,  3,  4,  5]])

# horizontal and Vertical stacking
Rules: Number of rows and columns must be same

In [107]:
np.hstack([data,data])

array([[11,  6, 17,  2, 19, 11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2, 18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6, 12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10, 17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7,  6, 16, 19, 15,  7]])

In [108]:
np.vstack([data,data])

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])